name: Run golangci-lint

on:
  pull_request:
    branches: ["*"]
    paths: ["**/*.go", "go.*", ".golangci.yml", "internal/cgo/resources/*"]
  push:
    branches: ["*"]
    tags-ignore: ["v*"]
    paths: ["**/*.go", "go.*", ".golangci.yml", "internal/cgo/resources/*"]
  workflow_dispatch:

jobs:
  golangci-lint:
    name: CGO_ENABLED=${{ matrix.CGO_ENABLED }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CGO_ENABLED: ["0", "1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        env:
          CGO_ENABLED: ${{ matrix.CGO_ENABLED }}
