name: Run govulncheck

on:
  schedule:
    - cron: "0 0 * * Sun"
  pull_request:
    branches: ["*"]
    paths: ["**/*.go", "go.*", "internal/cgo/resources/*"]
  push:
    branches: ["*"]
    tags-ignore: ["v*"]
    paths: ["**/*.go", "go.*", "internal/cgo/resources/*"]
  workflow_dispatch:

jobs:
  govulncheck:
    name: CGO_ENABLED=${{ matrix.CGO_ENABLED }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CGO_ENABLED: ["0", "1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
        shell: bash

      - name: Run govulncheck
        run: govulncheck ./...
        shell: bash
        env:
          CGO_ENABLED: ${{ matrix.CGO_ENABLED }}
