name: Run tests

on:
  pull_request:
    branches: ["*"]
    paths: ["**/*.go", "go.*", "internal/cgo/resources/*"]
  push:
    branches: ["*"]
    tags-ignore: ["v*"]
    paths: ["**/*.go", "go.*", "internal/cgo/resources/*"]
  workflow_dispatch:

jobs:
  test:
    name: CGO_ENABLED=${{ matrix.CGO_ENABLED }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CGO_ENABLED: ["0", "1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run tests
        uses: robherley/go-test-action@v1
        env:
          LD_LIBRARY_PATH: ./internal/cgo/resources
